### ISSUE TITLE
Como crear layouts con thymeleaf

### ISSUE THREAD

**Issue by josdem** [softtek-gdl/softtek-meetups#27]

**Comment by Neku787** [comment]
Thymeleaf can include parts of other pages as fragments (whereas JSP only includes complete pages) using th:include (will include the contents of the fragment into its host tag) or th:replace (will actually substitute the host tag by the fragment’s). This allows the grouping of fragments into one or several pages. Look at the example. The home/homeNotSignedIn.html template is rendered when the anonymous user enters the home page of our application.

*For extra information please visit: 
http://www.thymeleaf.org/doc/articles/layouts.html
